Repository CMI-OSS/cbnu-alrami-client, pull requests merged in 2021-04, with the labels that each got.

#10 플로팅 버튼 기본 마크업
  src/assets/style/__pallette.css
  src/components/Notice/FloatingButton/index.tsx
  src/components/Notice/FloatingButton/style.ts
  src/components/Notice/index.tsx
Labels: markup

#15 feat: 식당 디테일페이지 제작
  src/apollo/quries/restaurant/restaurants.quries.ts
  src/assets/style/__pallette.css
  src/assets/style/globalStyle.ts
  src/components/Restaurant/Detail/index.tsx
  src/components/Restaurant/Detail/style.ts
  src/components/Restaurant/Shop/style.ts
  src/components/shared/Dialog/style.ts
Labels: feature

#17 feat - footer 제작
  src/apollo/index.ts
  src/assets/style/__pallette.css
  src/components/Cafeteria/Floating/style.ts
  src/components/Cafeteria/MenuList/Time/style.ts
  src/components/Cafeteria/Selector/Name/style.ts
  src/components/Cafeteria/Selector/style.ts
  src/components/Cafeteria/style.ts
  src/components/shared/Footer/index.tsx
  src/components/shared/Footer/style.ts
  src/index.tsx
Labels: feature, markup

#18 공지사항 상세 조회 다이얼로그 기본 마크업
  src/__mocks/notices.ts
  src/assets/style/__pallette.css
  src/components/Notice/FloatingButton/index.tsx
  src/components/Notice/FloatingButton/style.ts
  src/components/Notice/NoticeCardList/NoticeCard/index.tsx
  src/components/Notice/NoticeCardList/NoticeCard/style.ts
  src/components/Notice/NoticeCardList/index.tsx
  src/components/Notice/NoticeCardList/style.ts
  src/components/Notice/NoticeDetail/index.tsx
  src/components/Notice/NoticeDetail/style.ts
  src/components/Notice/Selector/index.tsx
  src/components/Notice/Selector/style.ts
Labels: markup

#23 Feature/13 calendar
  src/apollo/cache.ts
  src/apollo/field.ts
  src/apollo/index.ts
  src/apollo/quries/cafeteria/date.quries.ts
  src/apollo/quries/calendar/date.quries.ts
  src/apollo/quries/index.ts
  src/assets/style/__pallette.css
  src/components/Cafeteria/MenuList/index.tsx
  src/components/Cafeteria/Selector/Arrow/index.tsx
  src/components/Cafeteria/Selector/Date/index.tsx
  src/components/Schedule/Calendar/index.tsx
  src/components/Schedule/Calendar/style.ts
  src/components/Schedule/Label/index.tsx
  src/components/Schedule/Label/style.ts
  src/components/Schedule/index.tsx
  src/components/Schedule/style.ts
  src/components/shared/Footer/index.tsx
  src/constants/index.ts
  src/index.tsx
  src/utils/calendar.ts
  src/utils/day.ts
Labels: feature, markup

#22 [#21] refactor: openDialog hook
  src/components/Notice/NoticeCardList/NoticeCard/index.tsx
  src/hooks/useOpenDialog.ts
Labels: refactor
